---
title: Artenbijou
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
email: isa.bel@hotmail.com
description: Bijoux faites au sein d'une création unique en graines d'Amazonie
baseurl: "/artenbijou/"
url: https://github.com/defremont
instagram_username: artenbijou
phone: 33629665338
api_key: MDFhZjhmNTctYWZlMC00MzJlLWJiNjktZWU5MzRlYTQwOGZkNjM2MjY3ODM4NzkxODEzMTUx
markdown: kramdown
